#! /bin/sh

sxhkd &
compton --config ~/.config/compton/compton.conf -b & 
polybar bar &
feh --bg-scale ~/Pictures/bg.jpg &
devmon --no-gui &
mpd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           23

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config focus_by_distance true

bspc config normal_border_color '#928374'
bspc config focused_border_color '#ebdbb2'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#fb4934'
